### ISSUE TITLE
spelloutCardinal stopped working in a lot of languages

### ISSUE THREAD

**Issue by rotsee** [papandreou/node-cldr#145]
Since one of the latest releases, `renderSpelloutCardinal` no longer works for many languages

```
> cldr.extractRbnfFunctionByType("en").renderSpelloutCardinal(5)
'five' // OK
> cldr.extractRbnfFunctionByType("ja").renderSpelloutCardinal(5)
'五' // OK
> cldr.extractRbnfFunctionByType("es").renderSpelloutCardinal(5)
'5' // Expected 'cinco'
> cldr.extractRbnfFunctionByType("sv").renderSpelloutCardinal(5)
'5' // Expected 'fem'
```

Furthermore, in some languages, we now get an error:
```
> cldr.extractRbnfFunctionByType("ru").renderSpelloutCardinal(5)
Uncaught Error: Numeric literal whose value is NaN
    at generateNumber (/home/leo/newsworthy/textfunctions/node_modules/escodegen/escodegen.js:270:19)
    at CodeGenerator.Literal (/home/leo/newsworthy/textfunctions/node_modules/escodegen/escodegen.js:2360:24)
    at CodeGenerator.generateExpression (/home/leo/newsworthy/textfunctions/node_modules/escodegen/escodegen.js:2496:28)
    at CodeGenerator.BinaryExpression (/home/leo/newsworthy/textfunctions/node_modules/escodegen/escodegen.js:1856:29)
    at CodeGenerator.generateExpression (/home/leo/newsworthy/textfunctions/node_modules/escodegen/escodegen.js:2496:28)
    at CodeGenerator.BinaryExpression (/home/leo/newsworthy/textfunctions/node_modules/escodegen/escodegen.js:1846:29)
    at CodeGenerator.generateExpression (/home/leo/newsworthy/textfunctions/node_modules/escodegen/escodegen.js:2496:28)
    at CodeGenerator.ConditionalExpression (/home/leo/newsworthy/textfunctions/node_modules/escodegen/escodegen.js:1821:26)
    at CodeGenerator.generateExpression (/home/leo/newsworthy/textfunctions/node_modules/escodegen/escodegen.js:2496:28)
    at CodeGenerator.BinaryExpression (/home/leo/newsworthy/textfunctions/node_modules/escodegen/escodegen.js:1846:29)

```
(not sure if these errors are related or not)

**Comment by rotsee** [comment]
Never mind, I was too quick. This is actually not supposed to work in current CLDR. You need to specify a gender, using e.g. `cldr.extractRbnfFunctionByType("sv").renderSpelloutCardinalNeuter(5)`. I did not know that. Closing, but keeping this issue, in case someone else searches for a similar thing
